name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install markdown linter
        run: |
          npm install remark-cli remark-preset-lint-consistent

      - name: Fix markdown lint issues
        run: |
          npx remark . --use remark-preset-lint-consistent --output

      - name: Run markdown lint
        run: |
          npx remark . --use remark-preset-lint-consistent --frail
